model: "yolov11n"
image_size: 640
epochs: 100
batch_size: 16
roboflow:
  workspace: "giulianos-workspace-2isr5"
  project: "ski-3iie6"
  version: 8
  model_id: "giulianos-workspace-2isr5/ski-3iie6-8-yolo11n-t1"
  format: "yolov5pytorch"
inference:
  confidence: 0.35
  overlap: 0.50
